version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: sm_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: SistemaManutencao

  backend:
    build:
      context: ./backend/SistemaManutencao.API
      dockerfile: Dockerfile
    container_name: sm_backend
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=SistemaManutencao
      - JwtSettings__SecretKey=SistemaManutencao_SuperSecretKey_2024!_MustBe32CharsOrMore
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sm_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo_data:
